# Generated by Django 5.0.6 on 2024-07-02 08:51

from django.db import migrations, models
from django.conf import settings  # Import the settings module

class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='closing_time',
            field=models.DateField(),
        ),
    ]
