# # Generated by Django 5.0.6 on 2024-07-02 17:35

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('frontend', '0002_alter_product_closing_time'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='product',
#             name='posted_by',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.CreateModel(
#             name='Bid',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
#                 ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#                 ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='frontend.product')),
#             ],
#         ),
#     ]


# frontend/migrations/0003_product_posted_by_bid.py

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_product_closing_time'),  # Adjust the previous migration name
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
